[package]
name = "kernel"
version = "0.1.0"
authors = ["Hubert Jasudowicz <hubert.jasudowicz@cert.pl>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]
