name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build the kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - uses: docker://euantorano/zig:latest
        with:
          entrypoint: zig
          args: build install
