name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build the kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
      - uses: cachix/cachix-action@v10
        with:
          name: vmt
          extraPullNames: zig-nightly
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#vmt
